FROM ubuntu:22.04

RUN apt update && apt upgrade -y
RUN apt install -y build-essential ninja-build cmake git meson \
                   python3 python3-pip python3-setuptools python3-wheel python3-venv